language: cpp
os: linux
dist: bionic

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update
    # OpenCV used to read videos
    - sudo apt-get -y install libopencv-dev
    # rtmidi
    - sudo apt-get -y install librtmidi-dev
    # Lua, dependency of SOL
    - sudo apt-get -y install liblua5.3-dev
    # OpenGL libraries and friends
    - sudo apt-get -y install mesa-common-dev libgl1-mesa-dev libglfw3-dev libglu1-mesa-dev libglew-dev
    # Boost dependencies
    - sudo apt-get -y install libboost-signals-dev libboost-filesystem-dev libboost-system-dev
    - sudo pip install conan

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release

script: make && make test
