language: cpp
os: linux
dist: bionic

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update
    - sudo apt-get -y install libva-dev libvdpau-dev libpulse-dev libxcb1-dev libxcb-shm0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - sudo pip install conan

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release

script: make && make test
